[tool.ruff]
# Exclude commonly ignored directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "tests/",
    "*_test.py",
    "test_*.py",
    "solutions/"
]

# Line length and indentation settings, same as Black
line-length = 88
indent-width = 4

# Set target version to Python 3.12
target-version = "py312"

[tool.ruff.lint]
# Enable Pyflakes (F) and a subset of pycodestyle (E) codes by default
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fixes for all enabled rules when --fix is provided
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Enable formatter settings, similar to Black
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# Auto-formatting of code examples in docstrings is currently disabled by default
docstring-code-format = false
docstring-code-line-length = "dynamic"