[tool.ruff]
# Exclude commonly ignored directories (removed test excludes for fuller coverage; add back if needed)
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "solutions/"
]

# Line length bumped to 88 (Black default) for modern readability; aligns with PEP 8 flexibility
line-length = 88
indent-width = 4

# Set target version to Python 3.12
target-version = "py312"

[tool.ruff.lint]
# Expanded selection for better PEP coverage: E/W (PEP 8 style), F (flakes), D (PEP 257 docstrings),
# I (imports), UP (upgrades), B (bugbear), TYP (typing for PEP 484)
select = ["E", "W", "F", "D", "I", "UP", "B", "TYP"]
# Ignore optional docstring rules (e.g., no module/package docstrings for simple exercises)
ignore = ["D100", "D104", "D106"]

# Allow fixes for all enabled rules when --fix is provided
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pydocstyle]
# Explicitly use PEP 257 convention for docstrings
convention = "pep257"

[tool.ruff.format]
# Enable formatter settings, similar to Black
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings
docstring-code-format = true
docstring-code-line-length = "dynamic"

# Add mypy for PEP 484 type hint checking
[tool.mypy]
python_version = "3.12"
files = ["."]
exclude = ["solutions/", "\\.venv/", "venv/"]
strict = false  # Lenient for Exercism; set to true for stricter checks later
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true
disallow_any_generics = true
