---
name: "Flake8"

on:   # yamllint disable-line rule:truthy
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: "read"
  pull-requests: "read"

jobs:
  build:
    runs-on: "ubuntu-24.04"
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: "actions/checkout@v5"
      - name: "Cache PIP Dependencies"
        uses: "actions/cache@v4"
        with:
          path: "~/.cache/pip"
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python ${{ matrix.python-version }}
        # This is the version of the action for setting up Python,
        # not the Python version.
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current
      # Python version
      - name: "Display Python Version"
        run: python -c "import sys; print(sys.version)"
      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --no-cache-dir -r requirements.txt --upgrade
          python -m pip install pytest
      - name: "Install flake8"
        run: |
          python -m pip install flake8
      - name: "Check flake8 Version"
        run: |
          python -m flake8 --version
      - name: "Lint with flake8"
        # yamllint disable rule:line-length
        # stop the build if there are Python syntax errors or undefined names
        # exit-zero treats all errors as warnings.
        # The GitHub editor is 127 chars wide
        # Changing the Ignore List
        # W191 indentation contains tabs
        run: |
          python -m flake8 . --count --doctests --show-source --statistics
