---
name: "Main Pipeline"

on:  # yamllint disable-line rule:truthy
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: "read"
  pull-requests: "read"

jobs:
  yamllint:
    name: "YAML Lint Workflow"
    uses: "./.github/workflows/yamllint.yml"

  ruff:
    name: "Ruff Lint and Format"
    uses: "./.github/workflows/ruff.yml"
    needs:
      - "yamllint"

  pylint:
    name: "Pylint Workflow"
    uses: "./.github/workflows/pylint.yml"
    needs:
      - "yamllint"

  flake8:
    name: "Flake8 Workflow"
    uses: "./.github/workflows/flake8.yml"
    needs:
      - "yamllint"

  pytest:
    name: "Pytest Workflow"
    needs:
      - "ruff"
      - "pylint"
      - "flake8"
    uses: "./.github/workflows/pytest.yml"

  codecov:
    name: "Codecov Coverage Report"
    needs:
      - "pytest"
    uses: "./.github/workflows/codecov.yml"
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
